// ---------- DATA ----------
const arcos = [
  {n:'01', saga:'East Blue', nombre:'Romance Dawn / East Blue', nota:7.0,
   texto:'El arranque. Se nota que todavía se está construyendo el mundo, pero ya deja claro el tono: aventura ligera con un fondo trágico en cada isla.'},
  {n:'02', saga:'Alabasta', nombre:'Alabasta', nota:8.6,
   texto:'El primer arco donde la historia se siente "grande". Vivi y Crocodile elevan el nivel de las apuestas políticas del mundo por primera vez.'},
  {n:'03', saga:'Skypiea', nombre:'Skypiea', nota:7.3,
   texto:'El más "aparte" tonalmente, pero Enel es un villano memorable y el concepto del cielo como escenario todavía se siente original.'},
  {n:'04', saga:'Water 7', nombre:'Water 7 / Enies Lobby', nota:9.4,
   texto:'Probablemente el mejor tramo de todo el manga hasta ese punto. Usopp, Robin y Franky se ganan su lugar de una forma que ningún arco anterior había logrado.'},
  {n:'05', saga:'Thriller Bark', nombre:'Thriller Bark', nota:6.8,
   texto:'Más flojo en trama, pero cumple su función: unir a Brook a la tripulación y dar un respiro de terror-cómico antes de la guerra.'},
  {n:'06', saga:'Marineford', nombre:'Marineford / Guerra de los Mejores', nota:9.7,
   texto:'El punto de quiebre de la serie. La muerte de Ace y el grito de Luffy en Marineford siguen siendo de lo más citado del fandom por algo.'},
  {n:'07', saga:'Fishman Island', nombre:'Fishman Island', nota:7.5,
   texto:'Necesario para el tema del racismo entre razas del mundo, aunque el ritmo baja bastante después de la intensidad de Marineford.'},
  {n:'08', saga:'Dressrosa', nombre:'Dressrosa', nota:8.2,
   texto:'Larguísimo, pero paga bien: Law, la alianza y el pasado de Doflamingo con los Ángeles del Cielo dan uno de los mejores villanos de la serie.'},
  {n:'09', saga:'Whole Cake Island', nombre:'Whole Cake Island', nota:8.4,
   texto:'Big Mom es la mejor antagonista que ha tenido la serie hasta ahora, y el "escape" final es de lo más tenso que ha escrito Oda.'},
  {n:'10', saga:'Wano', nombre:'Wano Kuni', nota:9.0,
   texto:'Ambicioso al punto de sentirse eterno en algunos tramos, pero cierra con una de las batallas mejor coreografiadas de todo el manga.'},
  {n:'11', saga:'Egghead', nombre:'Egghead', nota:8.1,
   texto:'El arco más "de lore": Vegapunk suelta más información sobre el mundo en pocos capítulos que varios arcos anteriores juntos.'},
];

const personajes = [
  {tag:'Capitán', nombre:'Monkey D. Luffy', fruta:'Gomu Gomu no Mi (Hito Hito no Mi, Modelo: Nika)',
   texto:'Lo interesante no es que sea "el más fuerte", sino que su forma de pelear siempre refleja su forma de ver el mundo: libertad literal e improvisada.',
   dato:'Su fruta resultó ser una de las tres Zoan Míticas más buscadas del mundo, no una simple Paramecia.'},
  {tag:'Espadachín', nombre:'Roronoa Zoro', fruta:'Sin fruta del diablo',
   texto:'El único top-tier de la tripulación sin poder de fruta, lo cual hace que cada escalada suya se sienta ganada con entrenamiento puro.',
   dato:'Su meta declarada — superar a Mihawk — es de las pocas promesas de la serie que se ha mantenido intacta desde el arco 1.'},
  {tag:'Navegante', nombre:'Nami', fruta:'Sin fruta del diablo',
   texto:'Su arco de East Blue (Arlong Park) sigue siendo uno de los trasfondos mejor construidos de toda la serie, sin necesitar poderes para justificar su lugar en la tripulación.',
   dato:'Es la única capaz de manejar el Clima-Tact al nivel de crear un pequeño relámpago sin ser una usuaria de fruta.'},
  {tag:'Arqueóloga', nombre:'Nico Robin', fruta:'Hana Hana no Mi',
   texto:'Su historia conecta directamente con el misterio central del siglo vacío, lo que la vuelve clave en la trama más allá de su utilidad en combate.',
   dato:'Es la única superviviente confirmada de Ohara, la isla erudita destruida por un Buster Call.'},
  {tag:'Médico', nombre:'Tony Tony Chopper', fruta:'Hito Hito no Mi',
   texto:'El comic relief con más peso emocional de la tripulación — su historia con Hiluluk es de las que mejor resumen el tema de la serie sobre sueños heredados.',
   dato:'Su forma "Monstruo" es el resultado de comer Rumble Balls más allá del límite seguro.'},
  {tag:'Cirujano de la Muerte', nombre:'Trafalgar Law', fruta:'Ope Ope no Mi',
   texto:'Su fruta es, en teoría, la más versátil del manga (puede otorgar vida eterna a costa de la suya), lo que lo vuelve un objetivo constante para gente poderosa.',
   dato:'Fue uno de los "Supernovas" originales y ex-Corazón de la tripulación de Doflamingo antes de independizarse.'},
  {tag:'Antiguo Rey Pirata', nombre:'Gol D. Roger', fruta:'Sin fruta del diablo',
   texto:'Nunca lo vemos pelear en su época dorada, y aun así toda la serie gira en torno a la pregunta de qué encontró exactamente al llegar a Laugh Tale.',
   dato:'Murió de una enfermedad incurable, no en batalla — algo poco común para el "hombre más fuerte" de una era pirata.'},
  {tag:'Yonko', nombre:'Shanks', fruta:'Desconocida / sin confirmar en canon',
   texto:'Aparece poco en pantalla pero cada aparición reconfigura el tablero — el mero rumor de su llegada detiene guerras.',
   dato:'Perdió un brazo salvando a Luffy de niño, el evento que detona toda la historia.'},
];

const teorias = [
  {titulo:'Luffy es Joy Boy', prob:78,
   texto:'La Gear 5 se activó al "escuchar el tambor de la liberación" — el mismo lenguaje que se usa para describir al legendario Joy Boy. La conexión ya casi se siente confirmada más que teorizada.'},
  {titulo:'Imu es un Nefertari / familia real de Alabasta', prob:45,
   texto:'La corona y el trono con forma egipcia, sumado al asiento vacío número 20 en el Gorosei, apuntan a un vínculo con el reino que "traicionó" al mundo hace 800 años.'},
  {titulo:'El "One Piece" no es un tesoro material sino información histórica', prob:60,
   texto:'Todo indica que lo que Roger encontró en Laugh Tale fue la verdad completa del Siglo Vacío, no montañas de oro — coherente con el peso que la serie le da al conocimiento prohibido.'},
  {titulo:'Blackbeard tiene una fisiología distinta que le permite dos frutas', prob:65,
   texto:'Marco lo notó explícitamente: su cuerpo no reacciona como el de un usuario normal. Sea una enfermedad, una anomalía genética o algo relacionado con el Siglo Vacío, algo en él rompe las reglas conocidas.'},
  {titulo:'Los "Cinco Ancianos" ocultan una raza gigante o antigua distinta a la humana', prob:38,
   texto:'Sus formas de bestia mítica al liberar sus frutas Zoan sugieren un vínculo directo con las "razas antiguas" que existían antes del Siglo Vacío.'},
  {titulo:'Vegapunk sobrevive dividido entre sus satélites de forma permanente', prob:55,
   texto:'Con seis versiones operando de forma independiente, es probable que "Vegapunk" deje de ser una sola persona para convertirse en una red de conciencia distribuida.'},
];

const duelos = [
  {a:'Luffy (Gear 5)', b:'Katakuri', pa:82,
   texto:'Con Gear 5 activo, Luffy neutraliza justo la ventaja que hizo a Katakuri casi imbatible: la precognición del Mochi Mochi. Sin Gear 5, la pelea se invierte por completo.'},
  {a:'Zoro', b:'Mihawk (post-Wano)', pa:44,
   texto:'La brecha se cerró muchísimo tras Wano, pero Mihawk sigue teniendo la ventaja de 20+ años de experiencia como el mejor espadachín del mundo. Cerca, pero todavía no es un empate.'},
  {a:'Law', b:'Doflamingo', pa:38,
   texto:'En condiciones normales Doflamingo gana por resistencia y control de Haki, tal como se vio en el manga — Law necesitó ayuda externa (Luffy) para inclinar la balanza.'},
  {a:'Sanji (Ifrit Jambe)', b:'Queen', pa:70,
   texto:'La combinación de velocidad, Haki de armadura al rojo vivo y la resistencia genética de Queen hacen una pelea pareja, pero el fuego de Sanji termina marcando la diferencia.'},
  {a:'Whitebeard (en su pico)', b:'Blackbeard (post-Marineford)', pa:30,
   texto:'Whitebeard moribundo y ya sin la mitad de su poder casi lo derrota; en su mejor momento físico, antes de la guerra, la pelea ni siquiera sería cercana.'},
  {a:'Shanks', b:'Mihawk', pa:58,
   texto:'Ambos evitan pelear en serio en el canon, lo que hace esto más especulativo — pero el respeto mutuo constante en el manga sugiere una pelea muy pareja con ligera ventaja para Shanks.'},
];

const encuestaFavArco = [
  {n:'Marineford', p:27},
  {n:'Water 7 / Enies Lobby', p:22},
  {n:'Wano Kuni', p:18},
  {n:'Dressrosa', p:12},
  {n:'Alabasta', p:11},
  {n:'Whole Cake Island', p:10},
];
const encuestaFavPersonaje = [
  {n:'Luffy', p:24},
  {n:'Zoro', p:19},
  {n:'Law', p:14},
  {n:'Robin', p:13},
  {n:'Sanji', p:12},
  {n:'Nami', p:9},
  {n:'Chopper', p:9},
];
