// ---------- DATA ----------
// Orden cronológico canon (sin filler), con rango de capítulos aproximado,
// sinopsis breve y personajes principales de cada arco.
const arcos = [
  {n:'01', saga:'East Blue', nombre:'Romance Dawn', capitulos:'1–7',
   personajes:['Luffy','Zoro','Coby'],
   sinopsis:'Luffy zarpa solo de Fuusha Village, libera a Coby de la capitana Alvida y recluta a Zoro tras derrotar al marine corrupto Morgan "Puño de Hierro" en Shells Town.'},
  {n:'02', saga:'East Blue', nombre:'Orange Town', capitulos:'8–21',
   personajes:['Luffy','Zoro','Nami','Buggy'],
   sinopsis:'En Orange Town, Luffy y Zoro enfrentan a Buggy el Payaso y su tripulación; Nami se cruza en su camino con una tregua temporal antes de unirse más adelante.'},
  {n:'03', saga:'East Blue', nombre:'Syrup Village', capitulos:'22–41',
   personajes:['Luffy','Usopp','Kaya'],
   sinopsis:'En Syrup Village, Luffy se enfrenta al capitán pirata Kuro para proteger a la joven Kaya, y Usopp termina uniéndose a la tripulación.'},
  {n:'04', saga:'East Blue', nombre:'Baratie', capitulos:'42–68',
   personajes:['Sanji','Zoro','Mihawk'],
   sinopsis:'En el restaurante flotante Baratie se une Sanji tras el ataque del pirata Don Krieg, y Zoro tiene su primer y devastador cruce de espadas con Mihawk.'},
  {n:'05', saga:'East Blue', nombre:'Arlong Park', capitulos:'69–95',
   personajes:['Nami','Arlong','Luffy'],
   sinopsis:'Se revela el pasado de Nami y la opresión de su pueblo, Cocoyasi, bajo el hombre-pez Arlong; la tripulación libera la aldea de su dominio.'},
  {n:'06', saga:'East Blue', nombre:'Loguetown', capitulos:'96–100',
   personajes:['Luffy','Smoker','Buggy'],
   sinopsis:'De paso por la ciudad donde ejecutaron a Gol D. Roger, Luffy tiene su primer cruce cercano con el marine Smoker justo antes de entrar a la Grand Line.'},
  {n:'07', saga:'Alabasta', nombre:'Reverse Mountain / Whiskey Peak', capitulos:'101–114',
   personajes:['Vivi','Luffy'],
   sinopsis:'La tripulación entra a la Grand Line por la Montaña Reversa; en Whiskey Peak descubren que Vivi es la princesa de Alabasta, infiltrada en la organización criminal Baroque Works.'},
  {n:'08', saga:'Alabasta', nombre:'Little Garden', capitulos:'115–129',
   personajes:['Dorry','Broggy'],
   sinopsis:'En una isla prehistórica, la tripulación presencia el duelo de honor de un siglo entre los gigantes Dorry y Broggy, saboteado por el agente Mr. 3.'},
  {n:'09', saga:'Alabasta', nombre:'Drum Island', capitulos:'130–154',
   personajes:['Chopper','Wapol'],
   sinopsis:'En la isla invernal gobernada por el tirano Wapol, se revela el pasado de Chopper junto al Dr. Hiluluk, y el reno se une a la tripulación como médico.'},
  {n:'10', saga:'Alabasta', nombre:'Alabasta', capitulos:'155–217',
   personajes:['Vivi','Crocodile','Luffy'],
   sinopsis:'Enfrentamiento contra el Shichibukai Crocodile y Baroque Works para evitar una guerra civil en el reino de Alabasta; Robin se une a la tripulación al cierre del arco.'},
  {n:'11', saga:'Cielo', nombre:'Jaya', capitulos:'218–236',
   personajes:['Bellamy','Luffy'],
   sinopsis:'En la isla pirata de Jaya, la tripulación choca con el arrogante Bellamy y encuentra las primeras pistas creíbles sobre la existencia de islas en el cielo.'},
  {n:'12', saga:'Cielo', nombre:'Skypiea', capitulos:'237–302',
   personajes:['Enel','Luffy'],
   sinopsis:'Ascenso a la isla celeste de Skypiea, donde la tripulación se enfrenta al dios autoproclamado Enel por el destino de sus habitantes.'},
  {n:'13', saga:'Water 7', nombre:'Long Ring Long Land', capitulos:'303–321',
   personajes:['Foxy','Luffy'],
   sinopsis:'Torneo de "Davy Back Fight" contra los Piratas Foxy, donde se apuesta la libertad de miembros de la tripulación y hasta la bandera pirata.'},
  {n:'14', saga:'Water 7', nombre:'Water Seven', capitulos:'322–374',
   personajes:['Usopp','Robin','Franky'],
   sinopsis:'En la ciudad acuática de Water Seven se decide reemplazar el Going Merry, lo que provoca la salida temporal de Usopp, mientras Robin desaparece con el CP9.'},
  {n:'15', saga:'Water 7', nombre:'Enies Lobby', capitulos:'375–430',
   personajes:['Robin','Franky','Rob Lucci'],
   sinopsis:'Rescate de Robin en la fortaleza judicial de Enies Lobby contra los agentes del CP9; el Going Merry realiza su último viaje y Franky se une a la tripulación.'},
  {n:'16', saga:'Water 7', nombre:'Post-Enies Lobby', capitulos:'431–441',
   personajes:['Usopp','Franky'],
   sinopsis:'Regreso a Water Seven, construcción del Thousand Sunny y reconciliación formal de Usopp con la tripulación.'},
  {n:'17', saga:'Thriller Bark', nombre:'Thriller Bark', capitulos:'442–489',
   personajes:['Brook','Gecko Moria'],
   sinopsis:'Isla-barco gobernada por el Shichibukai Gecko Moria y sus zombis; la tripulación gana a Brook como músico tras un enfrentamiento por sombras robadas.'},
  {n:'18', saga:'Guerra de los Mejores', nombre:'Sabaody Archipelago', capitulos:'490–513',
   personajes:['Bartholomew Kuma','Kizaru'],
   sinopsis:'Primer contacto directo con un Almirante de la Marina y un Shichibukai; la tripulación entera es dispersada por el poder de Bartholomew Kuma.'},
  {n:'19', saga:'Guerra de los Mejores', nombre:'Amazon Lily', capitulos:'514–524',
   personajes:['Hancock','Luffy'],
   sinopsis:'Luffy llega a la isla de las guerreras Kuja, conoce a Boa Hancock y se entera de que su hermano Ace será ejecutado públicamente.'},
  {n:'20', saga:'Guerra de los Mejores', nombre:'Impel Down', capitulos:'525–549',
   personajes:['Luffy','Ace','Ivankov'],
   sinopsis:'Luffy se infiltra en la prisión submarina de máxima seguridad para intentar liberar a Ace, aliándose con presos como Ivankov y Buggy en el camino.'},
  {n:'21', saga:'Guerra de los Mejores', nombre:'Marineford', capitulos:'550–580',
   personajes:['Ace','Whitebeard','Barbanegra'],
   sinopsis:'La Guerra de los Mejores en Marineford: la muerte de Ace y de Whitebeard marca el punto de quiebre más doloroso de la serie hasta ese momento.'},
  {n:'22', saga:'Guerra de los Mejores', nombre:'Post-Guerra', capitulos:'581–597',
   personajes:['Luffy','Rayleigh'],
   sinopsis:'Luffy procesa su duelo tras Marineford y comienza un entrenamiento de dos años con Silvers Rayleigh antes de reunirse con su tripulación.'},
  {n:'23', saga:'Isla Gyojin', nombre:'Regreso a Sabaody', capitulos:'598–602',
   personajes:['Toda la tripulación'],
   sinopsis:'Tras dos años separados, los diez Sombrero de Paja se reencuentran en el Archipiélago Sabaody, listos para retomar su viaje.'},
  {n:'24', saga:'Isla Gyojin', nombre:'Fish-Man Island', capitulos:'603–653',
   personajes:['Hody Jones','Shirahoshi','Luffy'],
   sinopsis:'Conflicto racial entre humanos y hombres-pez bajo el mar, desatado por el extremista Hody Jones contra el reino de la princesa Shirahoshi.'},
  {n:'25', saga:'Dressrosa', nombre:'Punk Hazard', capitulos:'654–699',
   personajes:['Law','Caesar Clown'],
   sinopsis:'Isla dividida entre fuego y hielo donde la tripulación forma una alianza inicial con Trafalgar Law contra el científico Caesar Clown.'},
  {n:'26', saga:'Dressrosa', nombre:'Dressrosa', capitulos:'700–801',
   personajes:['Law','Doflamingo','Luffy'],
   sinopsis:'La alianza Luffy-Law se enfrenta al Shichibukai Doflamingo para liberar el reino de los juguetes y desmantelar su imperio criminal.'},
  {n:'27', saga:'Yonko', nombre:'Zou', capitulos:'802–824',
   personajes:['Mink','Jack'],
   sinopsis:'La tripulación llega a Zou, hogar de la tribu Mink, justo cuando es atacada por Jack "la Sequía", uno de los Calamidades de Kaido.'},
  {n:'28', saga:'Yonko', nombre:'Whole Cake Island', capitulos:'825–902',
   personajes:['Sanji','Big Mom'],
   sinopsis:'Rescate de Sanji de una boda arreglada con la temible familia Charlotte de la Yonko Big Mom, en el corazón de su territorio.'},
  {n:'29', saga:'Yonko', nombre:'Levely (Reverie)', capitulos:'903–908',
   personajes:['Vivi','Sabo','Imu'],
   sinopsis:'Reunión mundial de los reyes aliados al Gobierno Mundial, donde se insinúan secretos ocultos sobre el pasado y la misteriosa figura de Imu.'},
  {n:'30', saga:'Yonko', nombre:'Wano Kuni', capitulos:'909–1057',
   personajes:['Kaido','Luffy','Law'],
   sinopsis:'Una alianza masiva de piratas se enfrenta a la Yonko Kaido y al shogunato de Orochi para liberar al país aislado de Wano.'},
  {n:'31', saga:'Saga Final', nombre:'Egghead', capitulos:'1058–presente',
   personajes:['Vegapunk','Luffy','Bonney'],
   sinopsis:'La tripulación llega a la isla del científico Vegapunk, donde se revelan secretos largamente ocultos sobre el Siglo Vacío y el Gobierno Mundial.'},
];

const personajes = [
  {tag:'Capitán', nombre:'Monkey D. Luffy', fruta:'Gomu Gomu no Mi (Hito Hito no Mi, Modelo: Nika)',
   texto:'Lo interesante no es que sea "el más fuerte", sino que su forma de pelear siempre refleja su forma de ver el mundo: libertad literal e improvisada.',
   dato:'Su fruta resultó ser una de las tres Zoan Míticas más buscadas del mundo, no una simple Paramecia.',
   color:'#e2382c', icon:'hat', image:'images/luffy-emblem.jpg'},
  {tag:'Espadachín', nombre:'Roronoa Zoro', fruta:'Sin fruta del diablo',
   texto:'El único top-tier de la tripulación sin poder de fruta, lo cual hace que cada escalada suya se sienta ganada con entrenamiento puro.',
   dato:'Su meta declarada — superar a Mihawk — es de las pocas promesas de la serie que se ha mantenido intacta desde el arco 1.',
   color:'#2f8f5b', icon:'swords3', image:'images/zoro-emblem.jpg'},
  {tag:'Navegante', nombre:'Nami', fruta:'Sin fruta del diablo',
   texto:'Su arco de East Blue (Arlong Park) sigue siendo uno de los trasfondos mejor construidos de toda la serie, sin necesitar poderes para justificar su lugar en la tripulación.',
   dato:'Es la única capaz de manejar el Clima-Tact al nivel de crear un pequeño relámpago sin ser una usuaria de fruta.',
   color:'#e8952a', icon:'swirl', image:'images/nami-emblem.jpg'},
  {tag:'Tirador', nombre:'Usopp', fruta:'Sin fruta del diablo',
   texto:'Su arco como "Sniper King" es de los mejores ejemplos de cobardía convertida en coraje real — no deja de tener miedo, simplemente decide actuar de todos modos.',
   dato:'Su identidad de batalla, "Sogeking", nace de una mentira que termina volviéndose un rol heroico genuino.',
   color:'#4a9b8e', icon:'sling', image:'images/usopp-emblem.jpg'},
  {tag:'Cocinero', nombre:'Sanji', fruta:'Sin fruta del diablo',
   texto:'Pelea exclusivamente con las piernas por una promesa de nunca dañar sus manos de cocinero — un detalle pequeño que dice mucho de su código personal.',
   dato:'Su técnica Diable Jambe recalienta sus piernas hasta volverlas literalmente brasas ardientes.',
   color:'#c9962b', icon:'tie', image:'images/sanji-emblem.jpg'},
  {tag:'Médico', nombre:'Tony Tony Chopper', fruta:'Hito Hito no Mi',
   texto:'El comic relief con más peso emocional de la tripulación — su historia con Hiluluk es de las que mejor resumen el tema de la serie sobre sueños heredados.',
   dato:'Su forma "Monstruo" es el resultado de comer Rumble Balls más allá del límite seguro.',
   color:'#e07fa0', icon:'antler', image:'images/chopper-emblem.jpg'},
  {tag:'Arqueóloga', nombre:'Nico Robin', fruta:'Hana Hana no Mi',
   texto:'Su historia conecta directamente con el misterio central del siglo vacío, lo que la vuelve clave en la trama más allá de su utilidad en combate.',
   dato:'Es la única superviviente confirmada de Ohara, la isla erudita destruida por un Buster Call.',
   color:'#6a4fa0', icon:'flower', image:'images/robin-emblem.jpg'},
  {tag:'Carpintero', nombre:'Franky', fruta:'Sin fruta del diablo (mejoras cyborg)',
   texto:'Construyó su propio cuerpo cyborg tras un accidente, y ese mismo espíritu de "reconstruir algo roto en algo mejor" define tanto al Sunny como a él mismo.',
   dato:'Es el creador del Thousand Sunny, el barco que reemplazó al Going Merry tras Water 7.',
   color:'#3d7ab8', icon:'star', image:'images/franky-emblem.jpg'},
  {tag:'Músico', nombre:'Brook', fruta:'Yomi Yomi no Mi',
   texto:'Murió hace más de 50 años y volvió como esqueleto gracias a su fruta — toda su historia gira en torno a cumplir una promesa hecha mucho antes de conocer a esta tripulación.',
   dato:'Su fruta le devolvió el alma al cuerpo, pero solo después de que este ya se hubiera descompuesto por completo.',
   color:'#a5652f', icon:'music', image:'images/brook-emblem.jpg'},
  {tag:'Timonel', nombre:'Jinbe', fruta:'Sin fruta del diablo (Ictiantropo)',
   texto:'Fue de los primeros en advertirle a Luffy sobre el precio de la venganza, y su lealtad tardía a los Sombrero de Paja se siente más ganada que la de casi cualquier otro miembro.',
   dato:'Fue el primer Shichibukai en renunciar al cargo por voluntad propia, antes incluso de que el sistema fuera abolido.',
   color:'#d1652b', icon:'anchor', image:'images/jinbe-emblem.jpg'},
];

const almirantes = [
  {tag:'Almirante de Flota', nombre:'Sengoku "el Buda"', fruta:'Hito Hito no Mi, Modelo: Buda',
   texto:'Lideró la Marina durante la era de oro de la piratería y tomó la decisión más polémica de la organización: ejecutar a Ace pese a la rendición de Barbablanca.',
   dato:'Se retiró justo después de la Guerra de Marineford, dejando el cargo a Sakazuki.',
   color:'#c9a227', icon:'radiance', image:'images/sengoku-emblem.jpg'},
  {tag:'Almirante', nombre:'Kuzan "Aokiji"', fruta:'Hie Hie no Mi',
   texto:'Su filosofía de "justicia perezosa" choca directamente con la de Akainu, y esa diferencia terminó definiendo el rumbo de la Marina tras la guerra.',
   dato:'Perdió el puesto de Almirante de Flota frente a Sakazuki en un duelo que dejó una isla entera destruida.',
   color:'#4fd3e0', icon:'ice', image:'images/aokiji-emblem.jpg'},
  {tag:'Almirante de Flota', nombre:'Sakazuki "Akainu"', fruta:'Magu Magu no Mi',
   texto:'Su "justicia absoluta" no distingue entre civiles y combatientes — la muerte de Ace a manos suyas es la escena que más define su forma de pensar.',
   dato:'Su fruta es considerada superior en jerarquía elemental incluso frente al fuego normal, por ser lava.',
   color:'#c0392b', icon:'flame', image:'images/akainu-emblem.jpg'},
  {tag:'Almirante', nombre:'Borsalino "Kizaru"', fruta:'Pika Pika no Mi',
   texto:'Su actitud despreocupada contrasta con ser, en términos de velocidad pura, probablemente el usuario de Logia más rápido revelado hasta ahora.',
   dato:'Se mueve literalmente a la velocidad de la luz al usar su fruta, ignorando casi cualquier intento de esquivarlo.',
   color:'#e8c93a', icon:'beam', image:'images/kizaru-emblem.jpg'},
  {tag:'Almirante', nombre:'Issho "Fujitora"', fruta:'Zushi Zushi no Mi',
   texto:'Ciego por decisión propia tras un evento que lo hizo desconfiar de lo que ve, es de los pocos altos mandos que cuestiona abiertamente la corrupción del Gobierno Mundial.',
   dato:'Puede alterar la gravedad a su alrededor, al punto de invocar meteoritos durante la Batalla de Dressrosa.',
   color:'#8e5ec9', icon:'staff', image:'images/fujitora-emblem.jpg'},
  {tag:'Almirante', nombre:'Aramaki "Ryokugyu"', fruta:'Grow Grow no Mi (Zusa Zusa no Mi)',
   texto:'El más nuevo de los almirantes presentados, con una filosofía de desgaste: prefiere agotar a su enemigo antes que enfrentarlo de forma directa.',
   dato:'Fue nombrado almirante después de la caída del sistema de los Shichibukai, en el reordenamiento de poder de la Marina.',
   color:'#3d8f4c', icon:'leaf', image:'images/aramaki-emblem.jpg'},
];

const teorias = [
  {titulo:'Luffy es Joy Boy', prob:78,
   texto:'La Gear 5 se activó al "escuchar el tambor de la liberación" — el mismo lenguaje que se usa para describir al legendario Joy Boy. La conexión ya casi se siente confirmada más que teorizada.'},
  {titulo:'Imu es un Nefertari / familia real de Alabasta', prob:45,
   texto:'La corona y el trono con forma egipcia, sumado al asiento vacío número 20 en el Gorosei, apuntan a un vínculo con el reino que "traicionó" al mundo hace 800 años.'},
  {titulo:'El "One Piece" no es un tesoro material sino información histórica', prob:60,
   texto:'Todo indica que lo que Roger encontró en Laugh Tale fue la verdad completa del Siglo Vacío, no montañas de oro — coherente con el peso que la serie le da al conocimiento prohibido.'},
  {titulo:'Blackbeard tiene una fisiología distinta que le permite dos frutas', prob:65,
   texto:'Marco lo notó explícitamente: su cuerpo no reacciona como el de un usuario normal. Sea una enfermedad, una anomalía genética o algo relacionado con el Siglo Vacío, algo en él rompe las reglas conocidas.'},
  {titulo:'Los "Cinco Ancianos" ocultan una raza gigante o antigua distinta a la humana', prob:38,
   texto:'Sus formas de bestia mítica al liberar sus frutas Zoan sugieren un vínculo directo con las "razas antiguas" que existían antes del Siglo Vacío.'},
  {titulo:'Vegapunk sobrevive dividido entre sus satélites de forma permanente', prob:55,
   texto:'Con seis versiones operando de forma independiente, es probable que "Vegapunk" deje de ser una sola persona para convertirse en una red de conciencia distribuida.'},
];

const duelos = [
  {a:'Luffy (Gear 5)', b:'Katakuri', pa:82,
   texto:'Con Gear 5 activo, Luffy neutraliza justo la ventaja que hizo a Katakuri casi imbatible: la precognición del Mochi Mochi. Sin Gear 5, la pelea se invierte por completo.'},
  {a:'Zoro', b:'Mihawk (post-Wano)', pa:44,
   texto:'La brecha se cerró muchísimo tras Wano, pero Mihawk sigue teniendo la ventaja de 20+ años de experiencia como el mejor espadachín del mundo. Cerca, pero todavía no es un empate.'},
  {a:'Law', b:'Doflamingo', pa:38,
   texto:'En condiciones normales Doflamingo gana por resistencia y control de Haki, tal como se vio en el manga — Law necesitó ayuda externa (Luffy) para inclinar la balanza.'},
  {a:'Sanji (Ifrit Jambe)', b:'Queen', pa:70,
   texto:'La combinación de velocidad, Haki de armadura al rojo vivo y la resistencia genética de Queen hacen una pelea pareja, pero el fuego de Sanji termina marcando la diferencia.'},
  {a:'Whitebeard (en su pico)', b:'Blackbeard (post-Marineford)', pa:30,
   texto:'Whitebeard moribundo y ya sin la mitad de su poder casi lo derrota; en su mejor momento físico, antes de la guerra, la pelea ni siquiera sería cercana.'},
  {a:'Shanks', b:'Mihawk', pa:58,
   texto:'Ambos evitan pelear en serio en el canon, lo que hace esto más especulativo — pero el respeto mutuo constante en el manga sugiere una pelea muy pareja con ligera ventaja para Shanks.'},
];

const encuestaFavArco = [
  {n:'Marineford', p:27},
  {n:'Water 7 / Enies Lobby', p:22},
  {n:'Wano Kuni', p:18},
  {n:'Dressrosa', p:12},
  {n:'Alabasta', p:11},
  {n:'Whole Cake Island', p:10},
];
const encuestaFavPersonaje = [
  {n:'Luffy', p:24},
  {n:'Zoro', p:19},
  {n:'Law', p:14},
  {n:'Robin', p:13},
  {n:'Sanji', p:12},
  {n:'Nami', p:9},
  {n:'Chopper', p:9},
];
